branch-defaults:
  dev:
    environment: null
    group_suffix: null
  workspace:
    environment: django-env
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
