# Generated by Django 4.1.3 on 2022-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
