# Generated by Django 4.1.4 on 2022-12-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_alter_dog_id_alter_dog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('age', models.IntegerField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=500)),
                ('bio', models.TextField()),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dog.dog')),
            ],
        ),
    ]
