# Generated by Django 4.1.3 on 2022-12-09 15:52

from django.db import migrations, models
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.generate_upload_path)),
                ('city', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('bio', models.TextField()),
            ],
        ),
    ]
