# Generated by Django 4.1.3 on 2022-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('age', models.IntegerField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('dog_id', models.IntegerField(max_length=2)),
                ('img', models.CharField(max_length=500)),
                ('bio', models.TextField()),
            ],
        ),
    ]
